sudo: required
dist: xenial
language: python
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive texlive-full python-pygments pandoc
script:
- make paper/paper.tex
- cd paper && pdflatex -interaction=nonstopmode -shell-escape paper.tex 
before_deploy:
    # Set up git user name and tag this commit
    - git config --local user.name "Siddharth Bhat"
    - git config --local user.email "siddu.druid@gmail.com"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: 627cbf220d2d5392e3abd830052881711dcc7b95
  file: paper/paper.pdf
  skip_cleanup: true
  draft: false
  overwrite: true
  on:
      all_branches: true
